Queries and update animals table
arnoldnekemiah/vet-clinic-database pull request #2
Opened 2023-09-20 16:01 UTC by arnoldnekemiah

-Made more Queries and Altered the` animals` table as suggested.
-Made use of Transactions to play with the animal table.
-Made use of Aggregate functions.

Below are the Screenshots for the results;

![update1](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/70dde597-8a75-43de-b979-2292a6d7f88a)

![update2](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/2e39fe07-6286-4592-950e-ea714b8c6729)

![update3](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/e2fc0bb2-ad39-44ea-a3fe-c837bc09289f)

![update4](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/23844815-42c9-45ce-aedf-a51860a4d8d4)

![update5](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/2ea54130-b202-4018-a015-b0ab79eed84a)

![image](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/39ef9856-1cec-4302-a656-d5ac9d94e155)

![update7](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/de1796ac-fdbd-40b9-a9fa-8397a1d3dc2e)

![update8](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/a5fc7862-88d9-46ab-b423-6bafd8147274)

![update9](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/ca12f9b5-9fe8-4c85-87ee-9935face2c16)

2023-09-20 16:21 UTC, Deepakdanger requested changes
Hi @arnoldnekemiah , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 16:21 UTC, Deepakdanger commented on queries.sql
> +
-[ ] Here need 2 more transaction
1. - UPDATE the animals table by setting the species column to digimon for all animals that have a name ending in mon.

  - UPDATE the animals table by setting the species column to pokemon for all animals that don't have species already set.
  - Commit the transaction.
```
   BEGIN;
   UPDATE animals SET species = 'digimon' WHERE name LIKE '%mon'; 
   UPDATE animals SET species = 'pokemon' WHERE species IS NULL; 

   SELECT species from animals; -- verify that change was made
   COMMIT;
   SELECT species from animals; -- verify that change persists after commit
```
2. Inside a transaction delete all records in the animals table, then roll back the transaction.

```sql
   BEGIN;

   DELETE FROM animals WHERE ;
   SELECT COUNT(*) FROM ANIMALS;

   ROLLBACK;
   SELECT COUNT(*) FROM ANIMALS;
```

2023-09-20 16:21 UTC, Deepakdanger commented on queries.sql
> +SELECT species, AVG(escape_attempts) AS avg_escape_attempts FROM animals WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-12-31' GROUP BY species;
- Here we have to run more query .
- [ ] What is the average weight of animals?
- [ ] What is the minimum and maximum weight of each type of animal?
- kindly attach a screenshot of this also

2023-09-21 09:53 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @arnoldnekemiah 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correctly made changes to queries ✔
- Correct use of Git Flow ✔
- Descriptive PR title with a great summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 09:53 UTC, AbelG101 commented on queries.sql
- [ ] As mentioned previously please make sure to update the screenshots on the PR description with the new query results.

2023-09-21 10:42 UTC, arnoldnekemiah commented on queries.sql
Hey @AbelG101, I updated the screenshots check the last two screenshots

2023-09-21 10:42 UTC, arnoldnekemiah commented on queries.sql
I had forgotten to click update

2023-09-21 10:57 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @arnoldnekemiah ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Added screenshots to the pull request description ✔️
- Created queries to answer the questions in
transactions ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 12:36 UTC, merged