Querry Multiple tables
arnoldnekemiah/vet-clinic-database pull request #3
Opened 2023-09-21 16:20 UTC by arnoldnekemiah

- Used primary key & foreign key mechanism for joining tables.
- Queried multiple tables.
- Prepared complex queries that answer analytical questions.

_Below are the Screenshots;_
![new1](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/0d2498b5-e11c-43a6-9e17-4ef33e254ea4)

![new2](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/b07f44e7-5857-4e2c-a5c6-da5c65a990e6)

![new3](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/4cd13a10-9011-4d54-9830-c4b6b21612f9)

![new4](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/d1e625f7-9681-473f-9256-281e209ece34)

![new5](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/2ba818e3-7e03-4880-99c7-4265e8bfeedd)

![new6](https://github.com/arnoldnekemiah/vet-clinic-database/assets/42886828/a991e45d-f95c-4595-8cf3-fd47f6482fd7)

2023-09-21 20:03 UTC, Bantealem requested changes
# Status: change required 
Hi @arnoldnekemiah, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Correct Git flow
- [x] Descriptive PD summary

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 20:03 UTC, Bantealem commented on queries.sql
> +ALTER TABLE animals ADD COLUMN species_id INTEGER REFERENCES species(id), ADD COLUMN owner_id INTEGER REFERENCES owners(id);
Great job so far. It would be better to put everything that creates or changes the table structure in the `schema.sql` file. It helps to make your code base understandable and clear and also it is one of the project requirements. Kindly, move this code to your `schema.sql` file.

![image](https://github.com/arnoldnekemiah/vet-clinic-database/assets/101523582/8a8cc28c-eb1a-4a8b-8db4-547e02091f89)

2023-09-21 20:03 UTC, Bantealem commented on data.sql
> +
Please insert data to the `owners` table. Currently, I can't see the data inserted into the `owners` table.  Kindly, add it.

![image](https://github.com/arnoldnekemiah/vet-clinic-database/assets/101523582/036a7faf-dafa-4436-94ca-f278a0b05db4)

2023-09-21 20:03 UTC, Bantealem commented on queries.sql
> +SELECT name FROM animals WHERE species_id = (SELECT id FROM species WHERE name = 'Pokemon');
Kindly, use the word `JOIN` to answer the question. since  It indicates that you want to combine data from the `animals` table with data from the `owners` table. the same for the `species` table.

![image](https://github.com/arnoldnekemiah/vet-clinic-database/assets/101523582/78464ffa-775c-4bad-959d-cee8de7ace0a)

2023-09-22 05:43 UTC, bienvenuushindi approved these changes
Hi @bienvenuushindi   , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights


- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-09-22 06:11 UTC, merged